export const samples: { [key: string]: string[] } = {
  creativeWriting: [
    "Simulate a conversation between [character 1] and [character 2] discussing [topic].",
    "Imagine a world where [unusual element] exists. Write a story about [character] who encounters [challenge] and how they overcome it using [unique solution].",
    "Write a [genre] story set in [time period] where the main character is a [profession] facing [challenge].",
    "Imagine an ancient civilization that thrived in [specific unlikely location].",
    "Describe a fictional ecosystem where [specific element] dominates.",
    "Imagine a futuristic mode of transportation and describe how it works.",
    "Describe a utopian society where [unique element] is the norm. Describe daily life there.",
    "Imagine a festival dedicated to celebrating [specific aspect of life or nature].",
    "Create a trivia game based on [specific subject].",
    "Write about a day in the life of someone living in [extreme climate or environment].",
    "Imagine a wildlife reserve for [specific animals]. What would it include?",
    "Imagine a futuristic zoo that includes [specific type of animal].",
    "Design a unique board game concept based on [specific theme].",
  ],
  personalDevelopment: [
    "Discuss the importance of [personal development topic]. Provide practical tips and strategies for improving in this area, and share any personal experiences or success stories.",
    "Explain how to start a collection of [specific items, e.g., coins, stamps].",
    "Create a bucket list for someone who loves [specific interest, e.g., marine life, stargazing].",
    "Create a mindfulness exercise for managing [specific emotion or situation].",
    "Provide personalized advice for [type of individual] looking to [goal]. Include steps they should take, potential challenges they may face, and resources they can use to succeed. Tailor the advice based on [specific context].",
  ],
  travelAndAdventure: [
    "List the top [number] destinations for [type of travel, e.g., adventure, relaxation].",
    "Plan a weekend itinerary for visiting [specific city or destination].",
    "Create a packing list for [type of trip] during [specific season].",
    "Plan a wildlife safari in [specific region or country].",
    "Create a travel guide for [specific region] on a budget.",
    "Plan a guided tour for [specific type of group, e.g., photographers, birdwatchers].",
    "Describe the unique flora and fauna of [specific habitat, e.g., rainforests, deserts].",
    "List the top [number] landmarks to visit in [specific country or city].",
    "Explain how to plan a camping trip for [specific terrain or weather].",
    "Design a trail map for hikers in [specific region].",
  ],
  scienceAndEducation: [
    "Explain the impact of [technology] on [industry/field]. Discuss the benefits, challenges, and future trends related to this technology.",
    "Explain the basics of [specific field of science] to a beginner.",
    "Describe how [natural phenomenon] occurs and its impact on the environment.",
    "Explain the lifecycle of a [animal/plant] in [specific ecosystem].",
    "Explain the science behind [specific natural event, e.g., auroras, volcanoes].",
    "Discuss the historical importance of [specific mode of transportation, e.g., railroads, ships].",
    "Create a curriculum for teaching [topic] to [target audience]. The curriculum should span [timeframe] and include learning objectives, daily or weekly lesson plans, recommended resources, practical exercises, and evaluation methods.",
    "Explain the process of brewing or making [specific beverage].",
    "Describe the process of preserving [specific type of food].",
    "Explain how [specific historical invention] changed society.",
  ],
  fitnessAndLifestyle: [
    "Design a [type of workout] plan for [fitness level] individuals aiming to [goal] in [timeframe].",
    "Explain the benefits of [type of exercise] for [specific group of people].",
    "Create a workout challenge for [specific goal, e.g., flexibility, strength].",
    "Plan a [type of garden] for [specific purpose].",
    "Create a recipe for [specific type of cuisine or dessert].",
    "Plan a themed picnic for [specific occasion].",
    "Describe the perfect menu for a [specific theme] dinner party.",
  ],
  historyAndCulture: [
    "Discuss the significance of [ancient festival or tradition] and how it is celebrated today.",
    "Explain the history and significance of [specific festival or celebration].",
    "Discuss the evolution of [specific dance form] over the centuries.",
    "Describe the cultural traditions of [fictional country or group].",
    "Describe the role of [specific plant or animal] in folklore or mythology.",
    "Discuss the symbolism of [specific natural element, e.g., trees, rivers] in art or literature.",
  ],
  problemSolving: [
    "Describe a scenario where [problem] arises in [context]. Provide a step-by-step approach to identify the root cause, propose [number] solutions, and evaluate their effectiveness. Include any tools or frameworks that could assist in resolving the issue.",
    "Perform a comparative analysis of [option 1] and [option 2] in the context of [specific use case]. Discuss their pros and cons, implementation requirements, costs, and suitability for [target audience]. Conclude with a recommendation and justification.",
    "Suggest [number] solutions for [problem] considering [constraints].",
    "Create a guide for assembling [specific type of kit, e.g., survival kit, craft kit].",
    "Design an adventure course for [specific type of outdoor activity].",
  ],
  eventPlanning: [
    "Plan a unique [type of party] for [specific occasion].",
    "Create a plan for a [type of event] for [number] people, including [specific requirement].",
    "Plan an educational field trip for [age group] to [specific location].",
    "Design a community event to raise awareness about [cause].",
    "Plan a family reunion with activities for [specific age groups].",
    "Plan a charity event to support [specific cause].",
    "Plan a cultural exchange event for [specific groups].",
    "Imagine a celebration in honor of [specific profession]. What activities would it include?",
  ],
};
